name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        architecture: x64
    - run: pip install -r requirements_dev.txt
    - run: flake8 cove_project/ cove_rdls/
